name: CI

on: [push, pull_request]

jobs:
  tue-ci:
    name: TUe CI - ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: TUe CI
        uses: tue-robotics/tue-env/ci/main@master
        with:
          image: ghcr.io/tue-robotics/tue-env-ros-noetic-cu12.1.1-cudnn8-devel
          package: ${{ github.event.repository.name }}
